### ISSUE TITLE
Ability to register dying

### ISSUE THREAD

**Issue by fredyvilla** [fredyvilla/opencog-to-minecraft#15]
Bot detects death

**Comment by NiteshBhutani** [comment]
hi, i wanted to take up this task. As i think this will be good to just get started with minecraft project for those who have high level knowledge of opencog. So any insight how to approacj this task?

**Comment by fredyvilla** [comment]
Nitesh,

Take a look at the Spockbot documentation to see if they already have an event or API to detect death/respawning. Once you identify the event, look at spockextras in opencog to build a bridge between spock and opencog. The last step is to let the action-gen controller that a death occurred. 

Fredy
