### ISSUE TITLE
Use clustering to identify block groups

### ISSUE THREAD

**Issue by fredyvilla** [fredyvilla/opencog-to-minecraft#17]
Bot clusters blocks into agglomerate to be able to identify areas.

**Comment by akhisud** [comment]
This clustering would be based on the definition of blocks in blocks.py (from spockbots), wouldn't it?

**Comment by akhisud** [comment]
I'd like to work on this, but a little more insight from someone experienced would greatly help. For instance, for what properties of 'areas' are we looking to identify areas?

**Comment by AndrewBuck** [comment]
One way to go about this is to use the categories facility in the grounded knowledge class.  Create a category for the kinds of things you want to group and then run a execute a bind link looking for blocks who are part of that class and one of their neighbors is as well.  Then you can look further at the blocks returned by the bind link and further group them into larger clusters or whatever you wanted to do with them.
